-- OPERAÇÕES EM LINHAS

SELECT * FROM VENDEDORES;

SELECT  NOME,
        JANEIRO,
        FEVEREIRO,
        MARCO,
        (JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
        TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3, 2) AS "MEDIA"
FROM VENDEDORES;


-- APLICANDO UMA PORCENTAGEM
SELECT  NOME,
        JANEIRO,
        FEVEREIRO,
        MARCO,
        (JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
        (JANEIRO+FEVEREIRO+MARCO) * 0.25 AS "DESCONTO",
        TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3, 2) AS "MEDIA"
FROM VENDEDORES;


-- ALTERANDO TABELAS 

CREATE TABLE TABELA(
	COLUNA1 VARCHAR(30),
	COLUNA2 VARCHAR(30),
	COLUNA3 VARCHAR(30)
);

CREATE TABLE TABELA(
	COLUNA1 INT PRIMARY KEY AUTO_INCREMENT
);

--ADICIONANDO UMA PK
ALTER TABLE TABELA 
ADD PRIMARY KEY (COLUNA1);

--ADICIONANDO COLUNA SEM POSICAO. ULTIMA POSICAO
ALTER TABLE TABELA 
ADD COLUNA varchar(30);

ALTER TABLE TABELA 
ADD COLUNA100 INT;

--ADICIONANDO UMA COLUNA COM POSICAO
ALTER TABLE TABELA 
ADD COLUMN COLUNA4 VARCHAR(30) NOT NULL UNIQUE
AFTER COLUNA3;

--MODIFICANDO O TIPO DE UM CAMPO
ALTER TABLE TABELA
 MODIFY COLUNA2 DATE NOT NULL;

--RENOMEANDO O NOME DA TABELA
ALTER TABLE TABELA 
RENAME PESSOA;


CREATE TABLE TIME(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	TIME VARCHAR(30),
	ID_PESSOA VARCHAR(30)
);

--Foreign key
ALTER TABLE TIME 
ADD FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(COLUNA1);

-- VERIFICAR AS CHAVES
USE CLIENTE;

SHOW CREATE TABLE CLIENTE;

SHOW CREATE TABLE ENDERECO;


-- ORGANIZACAO DE CHAVES -CONSTRAINT (REGRA)

CREATE DATABASE ESTUDO_CHAVE;

CREATE TABLE CLIENTE(
	IDCLIENTE INT,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY(IDCLIENTE);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

SHOW CREATE TABLE TELEFONE;

-- DICIONARIO DE DADOS

SHOW DATABASES;

USE Information_schema;

STATUS

SHOW TABLES;


SELECT * FROM TABLE_CONSTRAINTS;

DESC TABLE_CONSTRAINTS;

+--------------------+-------------+------+-----+---------+-------+
| Field              | Type        | Null | Key | Default | Extra |
+--------------------+-------------+------+-----+---------+-------+
| CONSTRAINT_CATALOG | varchar(64) | NO   |     | NULL    |       |
| CONSTRAINT_SCHEMA  | varchar(64) | NO   |     | NULL    |       |
| CONSTRAINT_NAME    | varchar(64) | YES  |     | NULL    |       |
| TABLE_SCHEMA       | varchar(64) | NO   |     | NULL    |       |
| TABLE_NAME         | varchar(64) | NO   |     | NULL    |       |
| CONSTRAINT_TYPE    | varchar(11) | NO   |     |         |       |
| ENFORCED           | varchar(3)  | NO   |     |         |       |
+--------------------+-------------+------+-----+---------+-------+


SELECT  CONSTRAINT_SCHEMA AS "BANCO",
        TABLE_NAME AS "TABELA",
	      CONSTRAINT_NAME AS "NOME REGRA",
	      CONSTRAINT_TYPE AS "TIPO"
FROM TABLE_CONSTRAINTS;


SELECT  CONSTRAINT_SCHEMA AS "BANCO",
        TABLE_NAME AS "TABELA",
	      CONSTRAINT_NAME AS "NOME REGRA",
	      CONSTRAINT_TYPE AS "TIPO"
FROM TABLE_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = 'ESTUDO_CHAVE';



-- ACOES DE CONSTRAINTS


















