-- IFNULL

SELECT C.NOME, C.EMAIL, E.ESTADO, T.NUMERO
FROM CLIENTE C
  INNER JOIN ENDERECO E
  ON C.IDCLIENTE = E.ID_CLIENTE
  INNER JOIN TELEFONE T
  ON C.IDCLIENTE = T.ID_CLIENTE;


-- IFNULL(COLUNA, STRING_MSG)

SELECT  C.NOME, 
        IFNULL(C.EMAIL, 'NÃO TEM EMAIL'), 
        E.ESTADO, 
        T.NUMERO
FROM CLIENTE C
  INNER JOIN ENDERECO E
  ON C.IDCLIENTE = E.ID_CLIENTE
  INNER JOIN TELEFONE T
  ON C.IDCLIENTE = T.ID_CLIENTE;


SELECT  C.NOME, 
        IFNULL(C.EMAIL, 'NÃO TEM EMAIL') AS EMAIL, 
        E.ESTADO, 
        T.NUMERO
FROM CLIENTE C
  INNER JOIN ENDERECO E
  ON C.IDCLIENTE = E.ID_CLIENTE
  INNER JOIN TELEFONE T
  ON C.IDCLIENTE = T.ID_CLIENTE;




-- VIEW

SELECT  C.NOME, C.SEXO, 
        IFNULL(C.EMAIL, 'NÃO TEM EMAIL') AS EMAIL, 
        T.TIPO, T.NUMERO, 
        E.BAIRRO, E.CIDADE, E.ESTADO 
FROM CLIENTE C
  INNER JOIN ENDERECO E
  ON C.IDCLIENTE = E.ID_CLIENTE
  INNER JOIN TELEFONE T
  ON C.IDCLIENTE = T.ID_CLIENTE;



CREATE VIEW RELATORIO AS 
SELECT  C.NOME, C.SEXO, 
        IFNULL(C.EMAIL, 'NÃO TEM EMAIL') AS EMAIL, 
        T.TIPO, T.NUMERO, 
        E.BAIRRO, E.CIDADE, E.ESTADO 
FROM CLIENTE C
  INNER JOIN ENDERECO E
  ON C.IDCLIENTE = E.ID_CLIENTE
  INNER JOIN TELEFONE T
  ON C.IDCLIENTE = T.ID_CLIENTE;


SELECT * FROM RELATORIO;


-- LOCALIZAR MINHA VIEW NO DB

SHOW TABLES;

+--------------------+
| Tables_in_COMERCIO |
+--------------------+
| CLIENTE            |
| ENDERECO           |
| PRODUTO            |
| RELATORIO -> VIEW  |
| TELEFONE           |
+--------------------+

DROP VIEW RELATORIO;



CREATE VIEW V_RELATORIO AS 
SELECT  C.NOME, C.SEXO, 
        IFNULL(C.EMAIL, 'NÃO TEM EMAIL') AS EMAIL, 
        T.TIPO, T.NUMERO, 
        E.BAIRRO, E.CIDADE, E.ESTADO 
FROM CLIENTE C
  INNER JOIN ENDERECO E
  ON C.IDCLIENTE = E.ID_CLIENTE
  INNER JOIN TELEFONE T
  ON C.IDCLIENTE = T.ID_CLIENTE;


-- QUERY DA QUERY
SELECT NOME, NUMERO, ESTADO 
FROM V_RELATORIO;


-- UPDATE, INSERT E DELETE

INSERT INTO V_RELATORIO VALUES(
'ANDREIA','F','ANDREIA@UOL.COM.BR','CEL','873547864','CENTRO','VITORIA','ES'
);

ERROR 1394 (HY000): Can not insert into join view 'comercio.v_relatorio' without fields list
ERROR 1395 (HY000): Can not delete from join view 'comercio.v_relatorio'

DELETE FROM V_RELATORIO WHERE NOME = 'JORGE';

/* É PERMITIDO FAZER UPDATES EM VIEWS COM JOIN */

UPDATE V_RELATORIO SET NOME = 'JOSE' WHERE NOME = 'JORGE';




-- ORDER BY


CREATE TABLE ALUNOS(
	NUMERO INT,
	NOME VARCHAR(30)
);

INSERT INTO ALUNOS VALUES(1,'JOAO');
INSERT INTO ALUNOS VALUES(1,'MARIA');
INSERT INTO ALUNOS VALUES(2,'ZOE');
INSERT INTO ALUNOS VALUES(2,'ANDRE');
INSERT INTO ALUNOS VALUES(3,'CLARA');
INSERT INTO ALUNOS VALUES(1,'CLARA');
INSERT INTO ALUNOS VALUES(4,'MAFRA');
INSERT INTO ALUNOS VALUES(5,'JANAINA');
INSERT INTO ALUNOS VALUES(1,'JANAINA');
INSERT INTO ALUNOS VALUES(3,'MARCELO');
INSERT INTO ALUNOS VALUES(4,'GIOVANI');
INSERT INTO ALUNOS VALUES(5,'ANTONIO');
INSERT INTO ALUNOS VALUES(6,'ANA');
INSERT INTO ALUNOS VALUES(6,'VIVIANE'); 

SELECT * FROM ALUNOS
ORDER BY NUMERO;

SELECT * FROM ALUNOS
ORDER BY 1;

SELECT * FROM ALUNOS
ORDER BY 2;

-- ORDENAR POR MAIS DE UMA COLUNA

SELECT * FROM ALUNOS
ORDER BY 1, 2;

SELECT * FROM ALUNOS
ORDER BY NUMERO, NOME;



-- ASC | DESC

SELECT * FROM ALUNOS
ORDER BY NUMERO ASC;

SELECT * FROM ALUNOS
ORDER BY NUMERO DESC;

SELECT * FROM ALUNOS
ORDER BY NUMERO DESC, NOME;

-- ORDENAR COM JOIN

SELECT  C.NOME, 
		C.SEXO, 
		IFNULL(C.EMAIL,'CLIENTE SEM EMAIL') AS "E-MAIL", 
		T.TIPO, 
		T.NUMERO, 
		E.BAIRRO, 
		E.CIDADE, 
		E.ESTADO
FROM CLIENTE C 
  INNER JOIN TELEFONE T 
  ON C.IDCLIENTE = T.ID_CLIENTE 
  INNER JOIN ENDERECO E 
  ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY NOME;

SELECT * FROM V_RELATORIO
ORDER BY 1;

